
---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Initialize the Kubernetes cluster using kubeadm
  when: reset_cluster is succeeded
  shell: |
    {{lookup('file', 'join-command-control-plane') }} --apiserver-advertise-address="{{ ansible_host }}"
  register: init_cluster
  # See: https://github.com/jetstack/cert-manager/issues/2640 with using kubeadm + calico + cert-manager
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -f /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
