
---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Initialize the Kubernetes cluster using kubeadm
  when: reset_cluster is succeeded
  shell: |
    {{lookup('file', 'join-command-worker-node') }} --apiserver-advertise-address="{{ ansible_host }}" --ignore-preflight-errors='Mem'
  # See: https://github.com/jetstack/cert-manager/issues/2640 with using kubeadm + calico + cert-manager
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"