---

- name: Init control plane
  block:
    - name: Include task list in play
      import_tasks: 01_init_control_plane.yml
      tags: [ 'never', 'init-control-plane' ]
  when: inventory_hostname in groups['master'][0]
  become: true
  become_user: root

- name: Join control plane nodes
  block:
    - name: Include task list in play
      import_tasks: 02_join_control_plane.yml
      tags: [ 'never', 'join-control-plane' ]
  when: inventory_hostname not in groups['master'][0]
  become: true
  become_user: root

- name: Join worker nodes
  block:
    - name: Include task list in play
      import_tasks: 03_join_worker_node.yml
      tags: [ 'never', 'join-worker-node' ]
  when: inventory_hostname in groups['worker-node']
  become: true
  become_user: root