---

- ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10255/tcp
    - 6783/tcp
    - 6784/tcp
    - 6783/udp
    - 6784/udp
  register: firewalld
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and inventory_hostname in groups['control_plane']
  tags: [firewall]

- ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 30000-32767/tcp
    - 10250/tcp
    - 6783/tcp
    - 6784/tcp
    - 6783/udp
    - 6784/udp
  register: firewalld
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and inventory_hostname in groups['worker_node']
  tags: [firewall]

- name: Allow iptables
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.dport }}"
    ctstate: NEW
    match: state
    jump: ACCEPT
    comment: "{{ item.comment }}"
  with_items:
  - { protocol: tcp, dport: 6783, comment: "Accept Weave Net connections."}
  - { protocol: udp, dport: 6783, comment: "Accept Weave Net connections."}
  - { protocol: udp, dport: 6784, comment: "Accept Weave Net connections."}
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [firewall]
  register: iptables

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and (firewalld.changed or iptables.changed)
  tags: [firewall]