all:
  children:
    control_plane:
      hosts:
        centos8-control-plane-01:
          ansible_ssh_user: vagrant
          ansible_host: 172.19.8.101
          ansible_port: 22
          ansible_ssh_private_key_file: ./.vagrant/machines/centos8-control-plane-01/virtualbox/private_key
          #ansible_ssh_common_args: '-F centos8-control-plane-01.cfg'
        centos8-control-plane-02:
          ansible_ssh_user: vagrant
          ansible_host: 172.19.8.102
          ansible_port: 22
          ansible_ssh_private_key_file: ./.vagrant/machines/centos8-control-plane-02/virtualbox/private_key
          #ansible_ssh_common_args: '-F centos8-control-plane-02.cfg'
        centos8-control-plane-03:
          ansible_ssh_user: vagrant
          ansible_host: 172.19.8.103
          ansible_port: 22
          ansible_ssh_private_key_file: ./.vagrant/machines/centos8-control-plane-03/virtualbox/private_key
          #ansible_ssh_common_args: '-F centos8-control-plane-03.cfg'
    worker_node:
      hosts:
        centos8-worker-node-01:
          ansible_ssh_user: vagrant
          ansible_host: 172.19.8.151
          ansible_port: 22
          ansible_ssh_private_key_file: ./.vagrant/machines/centos8-worker-node-01/virtualbox/private_key
          #ansible_ssh_common_args: '-F centos8-worker-node-01.cfg'
        centos8-worker-node-02:
          ansible_ssh_user: vagrant
          ansible_host: 172.19.8.152
          ansible_port: 22
          ansible_ssh_private_key_file: ./.vagrant/machines/centos8-worker-node-02/virtualbox/private_key
          #ansible_ssh_common_args: '-F centos8-worker-node-02.cfg'
        centos8-worker-node-03:
          ansible_ssh_user: vagrant
          ansible_host: 172.19.8.153
          ansible_port: 22
          ansible_ssh_private_key_file: ./.vagrant/machines/centos8-worker-node-03/virtualbox/private_key
          #ansible_ssh_common_args: '-F centos8-worker-node-03.cfg'