---

- ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  with_items:
    - 8443/tcp
  register: firewalld

- name: Allow iptables
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.dport }}"
    ctstate: NEW
    match: state
    jump: ACCEPT
    comment: "{{ item.comment }}"
  with_items:
  - { protocol: tcp, dport: 8443, comment: "Accept vip keepalived connections."}
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [firewall]
  register: iptables

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and firewalld.changed