---

- name: Install keepalived 
  dnf:
    name: keepalived-2.1.5-6.el8
    state: present

- name: Copy check_apiserver.sh file
  ansible.builtin.copy:
    src: "check_apiserver.sh"
    dest: /etc/keepalived/check_apiserver.sh
    backup: yes
    owner: root
    group: root
    mode: '0744'
  register: keepalived_check

- name: Copy keepalived.conf file
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: keepalived_conf

- name: Start keepalived service
  service:
    name: keepalived
    daemon_reload: yes
    state: reloaded
    enabled: yes
  when: keepalived_check.changed or keepalived_conf.changed